### ISSUE TITLE
"Cannot read property of user_id undefined"

### ISSUE THREAD

**Issue by theman0123** [Neighborhoodwatch/neighborhoodwatch#82]
This error appears everywhere. is it related to user on sessions/cookie?

**Comment by uncoolplane** [comment]
![image](https://cloud.githubusercontent.com/assets/1521327/26749479/e51a3d4c-47c8-11e7-856a-495702c362ee.png)

**Comment by uncoolplane** [comment]
Ryan Bryce
[1:42 AM] 
I had left a few console logs that were no longer needed. And i had also found that i was assigning values to variables on $scope that were coming from express sessions, but their values didn't exist yet because a user needed to be logged in for the data to be populated. So a few if statements checking against the boolean val on session that shows wether a user was logged in or not and it seamed to do the trick.
